/*
 * Sounds
 */
package thump.game.sound.sfx;

import thump.wad.sound.music.MusicInfo;
import static thump.game.sound.sfx.Sounds.SfxEnum.sfx_pistol;

/**
 *
 * @author mark
 */
public class Sounds {
//
// Identifiers for all music in game.
//

    public enum MusicEnum {
        mus_None,
        mus_e1m1,
        mus_e1m2,
        mus_e1m3,
        mus_e1m4,
        mus_e1m5,
        mus_e1m6,
        mus_e1m7,
        mus_e1m8,
        mus_e1m9,
        mus_e2m1,
        mus_e2m2,
        mus_e2m3,
        mus_e2m4,
        mus_e2m5,
        mus_e2m6,
        mus_e2m7,
        mus_e2m8,
        mus_e2m9,
        mus_e3m1,
        mus_e3m2,
        mus_e3m3,
        mus_e3m4,
        mus_e3m5,
        mus_e3m6,
        mus_e3m7,
        mus_e3m8,
        mus_e3m9,
        mus_inter,
        mus_intro,
        mus_bunny,
        mus_victor,
        mus_introa,
        mus_runnin,
        mus_stalks,
        mus_countd,
        mus_betwee,
        mus_doom,
        mus_the_da,
        mus_shawn,
        mus_ddtblu,
        mus_in_cit,
        mus_dead,
        mus_stlks2,
        mus_theda2,
        mus_doom2,
        mus_ddtbl2,
        mus_runni2,
        mus_dead2,
        mus_stlks3,
        mus_romero,
        mus_shawn2,
        mus_messag,
        mus_count2,
        mus_ddtbl3,
        mus_ampie,
        mus_theda3,
        mus_adrian,
        mus_messg2,
        mus_romer2,
        mus_tense,
        mus_shawn3,
        mus_openin,
        mus_evil,
        mus_ultima,
        mus_read_m,
        mus_dm2ttl,
        mus_dm2int
    }

//
// Identifiers for all sfx in game.
//
    public enum SfxEnum {
        sfx_None,
        sfx_pistol,
        sfx_shotgn,
        sfx_sgcock,
        sfx_dshtgn,
        sfx_dbopn,
        sfx_dbcls,
        sfx_dbload,
        sfx_plasma,
        sfx_bfg,
        sfx_sawup,
        sfx_sawidl,
        sfx_sawful,
        sfx_sawhit,
        sfx_rlaunc,
        sfx_rxplod,
        sfx_firsht,
        sfx_firxpl,
        sfx_pstart,
        sfx_pstop,
        sfx_doropn,
        sfx_dorcls,
        sfx_stnmov,
        sfx_swtchn,
        sfx_swtchx,
        sfx_plpain,
        sfx_dmpain,
        sfx_popain,
        sfx_vipain,
        sfx_mnpain,
        sfx_pepain,
        sfx_slop,
        sfx_itemup,
        sfx_wpnup,
        sfx_oof,
        sfx_telept,
        sfx_posit1,
        sfx_posit2,
        sfx_posit3,
        sfx_bgsit1,
        sfx_bgsit2,
        sfx_sgtsit,
        sfx_cacsit,
        sfx_brssit,
        sfx_cybsit,
        sfx_spisit,
        sfx_bspsit,
        sfx_kntsit,
        sfx_vilsit,
        sfx_mansit,
        sfx_pesit,
        sfx_sklatk,
        sfx_sgtatk,
        sfx_skepch,
        sfx_vilatk,
        sfx_claw,
        sfx_skeswg,
        sfx_pldeth,
        sfx_pdiehi,
        sfx_podth1,
        sfx_podth2,
        sfx_podth3,
        sfx_bgdth1,
        sfx_bgdth2,
        sfx_sgtdth,
        sfx_cacdth,
        sfx_skldth,
        sfx_brsdth,
        sfx_cybdth,
        sfx_spidth,
        sfx_bspdth,
        sfx_vildth,
        sfx_kntdth,
        sfx_pedth,
        sfx_skedth,
        sfx_posact,
        sfx_bgact,
        sfx_dmact,
        sfx_bspact,
        sfx_bspwlk,
        sfx_vilact,
        sfx_noway,
        sfx_barexp,
        sfx_punch,
        sfx_hoof,
        sfx_metal,
        sfx_chgun,
        sfx_tink,
        sfx_bdopn,
        sfx_bdcls,
        sfx_itmbk,
        sfx_flame,
        sfx_flamst,
        sfx_getpow,
        sfx_bospit,
        sfx_boscub,
        sfx_bossit,
        sfx_bospn,
        sfx_bosdth,
        sfx_manatk,
        sfx_mandth,
        sfx_sssit,
        sfx_ssdth,
        sfx_keenpn,
        sfx_keendt,
        sfx_skeact,
        sfx_skesit,
        sfx_skeatk,
        sfx_radio
    }

    public static final MusicInfo S_music[] = {
        null,
        new MusicInfo("e1m1", 0),
        new MusicInfo("e1m2", 0),
        new MusicInfo("e1m3", 0),
        new MusicInfo("e1m4", 0),
        new MusicInfo("e1m5", 0),
        new MusicInfo("e1m6", 0),
        new MusicInfo("e1m7", 0),
        new MusicInfo("e1m8", 0),
        new MusicInfo("e1m9", 0),
        new MusicInfo("e2m1", 0),
        new MusicInfo("e2m2", 0),
        new MusicInfo("e2m3", 0),
        new MusicInfo("e2m4", 0),
        new MusicInfo("e2m5", 0),
        new MusicInfo("e2m6", 0),
        new MusicInfo("e2m7", 0),
        new MusicInfo("e2m8", 0),
        new MusicInfo("e2m9", 0),
        new MusicInfo("e3m1", 0),
        new MusicInfo("e3m2", 0),
        new MusicInfo("e3m3", 0),
        new MusicInfo("e3m4", 0),
        new MusicInfo("e3m5", 0),
        new MusicInfo("e3m6", 0),
        new MusicInfo("e3m7", 0),
        new MusicInfo("e3m8", 0),
        new MusicInfo("e3m9", 0),
        new MusicInfo("inter", 0),
        new MusicInfo("intro", 0),
        new MusicInfo("bunny", 0),
        new MusicInfo("victor", 0),
        new MusicInfo("introa", 0),
        new MusicInfo("runnin", 0),
        new MusicInfo("stalks", 0),
        new MusicInfo("countd", 0),
        new MusicInfo("betwee", 0),
        new MusicInfo("doom", 0),
        new MusicInfo("the_da", 0),
        new MusicInfo("shawn", 0),
        new MusicInfo("ddtblu", 0),
        new MusicInfo("in_cit", 0),
        new MusicInfo("dead", 0),
        new MusicInfo("stlks2", 0),
        new MusicInfo("theda2", 0),
        new MusicInfo("doom2", 0),
        new MusicInfo("ddtbl2", 0),
        new MusicInfo("runni2", 0),
        new MusicInfo("dead2", 0),
        new MusicInfo("stlks3", 0),
        new MusicInfo("romero", 0),
        new MusicInfo("shawn2", 0),
        new MusicInfo("messag", 0),
        new MusicInfo("count2", 0),
        new MusicInfo("ddtbl3", 0),
        new MusicInfo("ampie", 0),
        new MusicInfo("theda3", 0),
        new MusicInfo("adrian", 0),
        new MusicInfo("messg2", 0),
        new MusicInfo("romer2", 0),
        new MusicInfo("tense", 0),
        new MusicInfo("shawn3", 0),
        new MusicInfo("openin", 0),
        new MusicInfo("evil", 0),
        new MusicInfo("ultima", 0),
        new MusicInfo("read_m", 0),
        new MusicInfo("dm2ttl", 0),
        new MusicInfo("dm2int", 0)
    };

//
// Information about all the sfx
//
    public static final SfxInfo S_sfx[] = {
        new SfxInfo("none", false, 0, null, -1, -1),  // S_sfx[0] needs to be a dummy for odd reasons.

        new SfxInfo("pistol", false, 64, null, -1, -1 ),
        new SfxInfo("shotgn", false, 64, null, -1, -1 ),
        new SfxInfo("sgcock", false, 64, null, -1, -1 ),
        new SfxInfo("dshtgn", false, 64, null, -1, -1 ),
        new SfxInfo("dbopn", false, 64, null, -1, -1 ),
        new SfxInfo("dbcls", false, 64, null, -1, -1 ),
        new SfxInfo("dbload", false, 64, null, -1, -1 ),
        new SfxInfo("plasma", false, 64, null, -1, -1 ),
        new SfxInfo("bfg", false, 64, null, -1, -1 ),
        new SfxInfo("sawup", false, 64, null, -1, -1 ),
        new SfxInfo("sawidl", false, 118, null, -1, -1 ),
        new SfxInfo("sawful", false, 64, null, -1, -1 ),
        new SfxInfo("sawhit", false, 64, null, -1, -1 ),
        new SfxInfo("rlaunc", false, 64, null, -1, -1 ),
        new SfxInfo("rxplod", false, 70, null, -1, -1 ),
        new SfxInfo("firsht", false, 70, null, -1, -1 ),
        new SfxInfo("firxpl", false, 70, null, -1, -1 ),
        new SfxInfo("pstart", false, 100, null, -1, -1 ),
        new SfxInfo("pstop", false, 100, null, -1, -1 ),
        new SfxInfo("doropn", false, 100, null, -1, -1 ),
        new SfxInfo("dorcls", false, 100, null, -1, -1 ),
        new SfxInfo("stnmov", false, 119, null, -1, -1 ),
        new SfxInfo("swtchn", false, 78, null, -1, -1 ),
        new SfxInfo("swtchx", false, 78, null, -1, -1 ),
        new SfxInfo("plpain", false, 96, null, -1, -1 ),
        new SfxInfo("dmpain", false, 96, null, -1, -1 ),
        new SfxInfo("popain", false, 96, null, -1, -1 ),
        new SfxInfo("vipain", false, 96, null, -1, -1 ),
        new SfxInfo("mnpain", false, 96, null, -1, -1 ),
        new SfxInfo("pepain", false, 96, null, -1, -1 ),
        new SfxInfo("slop", false, 78, null, -1, -1 ),
        new SfxInfo("itemup", true, 78, null, -1, -1 ),
        new SfxInfo("wpnup", true, 78, null, -1, -1 ),
        new SfxInfo("oof", false, 96, null, -1, -1 ),
        new SfxInfo("telept", false, 32, null, -1, -1 ),
        new SfxInfo("posit1", true, 98, null, -1, -1 ),
        new SfxInfo("posit2", true, 98, null, -1, -1 ),
        new SfxInfo("posit3", true, 98, null, -1, -1 ),
        new SfxInfo("bgsit1", true, 98, null, -1, -1 ),
        new SfxInfo("bgsit2", true, 98, null, -1, -1 ),
        new SfxInfo("sgtsit", true, 98, null, -1, -1 ),
        new SfxInfo("cacsit", true, 98, null, -1, -1 ),
        new SfxInfo("brssit", true, 94, null, -1, -1 ),
        new SfxInfo("cybsit", true, 92, null, -1, -1 ),
        new SfxInfo("spisit", true, 90, null, -1, -1 ),
        new SfxInfo("bspsit", true, 90, null, -1, -1 ),
        new SfxInfo("kntsit", true, 90, null, -1, -1 ),
        new SfxInfo("vilsit", true, 90, null, -1, -1 ),
        new SfxInfo("mansit", true, 90, null, -1, -1 ),
        new SfxInfo("pesit", true, 90, null, -1, -1 ),
        new SfxInfo("sklatk", false, 70, null, -1, -1 ),
        new SfxInfo("sgtatk", false, 70, null, -1, -1 ),
        new SfxInfo("skepch", false, 70, null, -1, -1 ),
        new SfxInfo("vilatk", false, 70, null, -1, -1 ),
        new SfxInfo("claw", false, 70, null, -1, -1 ),
        new SfxInfo("skeswg", false, 70, null, -1, -1 ),
        new SfxInfo("pldeth", false, 32, null, -1, -1 ),
        new SfxInfo("pdiehi", false, 32, null, -1, -1 ),
        new SfxInfo("podth1", false, 70, null, -1, -1 ),
        new SfxInfo("podth2", false, 70, null, -1, -1 ),
        new SfxInfo("podth3", false, 70, null, -1, -1 ),
        new SfxInfo("bgdth1", false, 70, null, -1, -1 ),
        new SfxInfo("bgdth2", false, 70, null, -1, -1 ),
        new SfxInfo("sgtdth", false, 70, null, -1, -1 ),
        new SfxInfo("cacdth", false, 70, null, -1, -1 ),
        new SfxInfo("skldth", false, 70, null, -1, -1 ),
        new SfxInfo("brsdth", false, 32, null, -1, -1 ),
        new SfxInfo("cybdth", false, 32, null, -1, -1 ),
        new SfxInfo("spidth", false, 32, null, -1, -1 ),
        new SfxInfo("bspdth", false, 32, null, -1, -1 ),
        new SfxInfo("vildth", false, 32, null, -1, -1 ),
        new SfxInfo("kntdth", false, 32, null, -1, -1 ),
        new SfxInfo("pedth", false, 32, null, -1, -1 ),
        new SfxInfo("skedth", false, 32, null, -1, -1 ),
        new SfxInfo("posact", true, 120, null, -1, -1 ),
        new SfxInfo("bgact", true, 120, null, -1, -1 ),
        new SfxInfo("dmact", true, 120, null, -1, -1 ),
        new SfxInfo("bspact", true, 100, null, -1, -1 ),
        new SfxInfo("bspwlk", true, 100, null, -1, -1 ),
        new SfxInfo("vilact", true, 100, null, -1, -1 ),
        new SfxInfo("noway", false, 78, null, -1, -1 ),
        new SfxInfo("barexp", false, 60, null, -1, -1 ),
        new SfxInfo("punch", false, 64, null, -1, -1 ),
        new SfxInfo("hoof", false, 70, null, -1, -1 ),
        new SfxInfo("metal", false, 70, null, -1, -1 ),
        new SfxInfo("chgun", false, 64, sfx_pistol, 150, 0 ),
        new SfxInfo("tink", false, 60, null, -1, -1 ),
        new SfxInfo("bdopn", false, 100, null, -1, -1 ),
        new SfxInfo("bdcls", false, 100, null, -1, -1 ),
        new SfxInfo("itmbk", false, 100, null, -1, -1 ),
        new SfxInfo("flame", false, 32, null, -1, -1 ),
        new SfxInfo("flamst", false, 32, null, -1, -1 ),
        new SfxInfo("getpow", false, 60, null, -1, -1 ),
        new SfxInfo("bospit", false, 70, null, -1, -1 ),
        new SfxInfo("boscub", false, 70, null, -1, -1 ),
        new SfxInfo("bossit", false, 70, null, -1, -1 ),
        new SfxInfo("bospn", false, 70, null, -1, -1 ),
        new SfxInfo("bosdth", false, 70, null, -1, -1 ),
        new SfxInfo("manatk", false, 70, null, -1, -1 ),
        new SfxInfo("mandth", false, 70, null, -1, -1 ),
        new SfxInfo("sssit", false, 70, null, -1, -1 ),
        new SfxInfo("ssdth", false, 70, null, -1, -1 ),
        new SfxInfo("keenpn", false, 70, null, -1, -1 ),
        new SfxInfo("keendt", false, 70, null, -1, -1 ),
        new SfxInfo("skeact", false, 70, null, -1, -1 ),
        new SfxInfo("skesit", false, 70, null, -1, -1 ),
        new SfxInfo("skeatk", false, 70, null, -1, -1 ),
        new SfxInfo("radio", false, 60, null, -1, -1 )
    };

}
