/*
 * View Panel - Game Graphics get drawn here.
 */
package thump.global;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import thump.game.Game;

/**
 *
 * @author mark
 */
@SuppressWarnings("serial")
public class ViewPanel extends javax.swing.JPanel {

            
    /**
     * Creates new form ViewPanel
     */
    public ViewPanel() {
        initComponents();
        
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); 
        
        
        BufferedImage screen = Game.getInstance().video.screenImage[0];
        
//        for (BufferedImage screen : screenImage) {
            g.drawImage(screen, 0, 0, this.getWidth(), this.getHeight(), this);
            
//        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
